---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(foreign) #for reading in the spss files
```

Located here --> 
/projects/cschifani/rTMSWM/task_fmri/behavioralData/

RTMS WM can get PANSS SANS WTAR MATRICS (?) 

https://edc.camhx.ca/redcap/surveys/?s=4JFL4HA7XH


This entire thing is still all SPINS formatty so gotta change that later.
```{r}
SPINS_pheno_pass <- read.csv("/projects/edickie/code/SZ_PINT/phenotypic/20200202_pheno_qapass.csv", stringsAsFactors = FALSE) %>% filter(., dataset=="SPINS")%>% mutate_all(trimws) %>% mutate_all(na_if,"NA") %>% mutate_all(na_if, "") %>% mutate_all(na_if, " ") 

qa_list <- SPINS_pheno_pass %>% select(., dataset,subject_id, sex = Sex, dx = DX, Age)
```

```{r}
data <- read.csv('/scratch/gherman/SCZ_PINT/data/saba/ClinicalData/SPINS/SPINS_DATA_2018-07-16.csv', stringsAsFactors= FALSE, na.strings=c("","NA", " ", "N/A"))  %>% mutate_all(trimws) %>% mutate_all(na_if,"NA") %>% mutate_all(na_if, "") %>% mutate_all(na_if, " ") %>%
  mutate(., subject_id= str_replace(substr(record_id, 7, 14), "_", ""))
  
```


```{r}
dx <- qa_list %>% select(., subject_id, dx)

```


```{r}
data2 <- data %>% mutate(., imaging_pass= ifelse((subject_id %in% qa_list$subject_id), 1, 0)) %>% merge(dx, by="subject_id", all.x=TRUE)


final_list <- data2 %>% filter(., imaging_pass == 1)

write.csv(final_list,'/projects/gherman/SZ_PINT/compiled_clinical/cleaner_data_sets/SPINS_arranged2020.csv')


```


```{r}
by_group<- final_list %>% group_by(dx)

by_group %>% summarize(total= sum(!is.na(subject_id)), n_wtar = sum(!is.na(wtar_std_score)), n_sans= sum(!is.na(sans_doa)), n_bprs = sum(!is.na(bprs_doa)), n_scid = sum(!is.na(scid5_dis1)))

```

